### ISSUE TITLE
Doesn't activate when backspacing to a tag

### ISSUE THREAD

**Issue by dsandstrom** [dsandstrom/atom-double-tag#1]
Example:

``` html
<div | class="css">
```

Hit backspace and it seems like you should be able to edit both tags at once.  Yet, the end tag doesn't respond to changes.  This is because Atom's backspace selects to the left, then deletes.  However, I'm not activating when there is a selection.

**Comment by UziTech** [comment]
I figured out the problem when backspacing but I'm not sure on the best solution.

The text editor handles a backspace by selecting the character to the left then deleting the selection so the only time the cursor changes position is when it selects the character to the left and `findTag` will return right away because `editorHasSelectedText` will return true. When the selection is deleted `onDidChangeCursorPosition` won't be called because the cursor doesn't change position.

You could solve this by subscribing to `onDidChangeSelectionRange`

```coffee
    @subscriptions.add @editor.onDidChangeSelectionRange (event) =>
      @reset() if @foundTag and @cursorLeftMarker()
      return if @foundTag

      @findTag(event.selection.cursor)
```

or by not checking for `editorHasSelectedText` in `findTag`

**Comment by dsandstrom** [comment]
Added a branch `allow-selection` if you want to test it out.  No problems so far.
