### ISSUE TITLE
Doesn't work in React

### ISSUE THREAD

**Issue by 0oMarko0** [dsandstrom/atom-double-tag#32]
If you are in a .js file and you want to edit some jsx for a react component the plugin doesn't work. I've tried multiple tag. Would be really useful to have that feature

**Comment by dsandstrom** [comment]
Change the file extension to `.jsx`.

**Comment by aacassandra** [comment]
it still doesn't work even though the file has been changed to .jsx

**Comment by valtido** [comment]
> Change the file extension to `.jsx`.

I think a better solution may be in order :) we can't simply rename every single file on existing projects as well as getting other peers to agree to this, to support an atom plugin for small added convenience.

Would love to see this thing work on React. Maybe it's best to look for the file type (grammar) rather than extensions to identify the file.

**Comment by dsandstrom** [comment]
@valtido You either have to change the filename or add enable for all js files. Up to you.
