### ISSUE TITLE
TextBuffer.setTextInRange is deprecated.

### ISSUE THREAD

**Issue by rcrooks** [dsandstrom/atom-double-tag#36]
just fyi

The `undo` option is deprecated. Call groupLastChanges() on the TextBuffer afterward instead.
```
TextBuffer.setTextInRange (<embedded>:33530:22)
TextEditor.setTextInBufferRange (<embedded>:3552:35)
DoubleTag.copyNewTagToStart (/Users/rcrooks/.atom/packages/double-tag/lib/double-tag.coffee:125:19)
<unknown> (/Users/rcrooks/.atom/packages/double-tag/lib/double-tag.coffee:81:26)
Function.module.exports.Emitter.simpleDispatch (<embedded>:66736:20)
Emitter.emit (<embedded>:66852:34)
```

**Comment by dsandstrom** [comment]
Well that sucks.  I switched to the recommended function `groupLastChanges()`, but redo is broken.  Moreover, it appears redo has been broken since Atom v1.25.

https://github.com/atom/atom/commit/72b664dc882ad1b12cccd2c7ef28c8924041af92
https://github.com/atom/atom/issues/16956
https://github.com/atom/text-buffer/pull/282

**Comment by rcrooks** [comment]
bummer. Thanks for working on it though - I use this package constantly!

**Comment by rcrooks** [comment]
Thanks for fixing!

**Comment by dsandstrom** [comment]
@rcrooks Thank you for the issue
