### ISSUE TITLE
Does not work with JSX

### ISSUE THREAD

**Issue by daiyi** [dsandstrom/atom-double-tag#40]
Not working in `.jsx` files. I checked the language scope and it is `source.js.jsx`.

**Comment by daiyi** [comment]
I solved my own problem! The atom package `language-javascript-jsx` must be downloaded and enabled. Recording here for posterity!

**Comment by dsandstrom** [comment]
Thanks for the info.  I looked into this more since I was having trouble with jsx files.

If you have the official `language-javascript` package enabled, the syntax used for jsx files is `source.js`.  So to get double-tag to work, you need to add `source.js` to the *Enabled Scopes* in double-tag's settings in Atom.

If you disable the official language package and instead use [language-javascript-jsx](https://atom.io/packages/language-javascript-jsx), the syntax for jsx files shows up as `source.js.jsx`, which is already included in the settings.

I'm hesitant to add `source.js` to the default settings.

Also, it seems the unofficial js package is archived, so not sure what's going on there.

Edit
Just realized I already found the unofficial replacement: [react](https://github.com/orktes/atom-react)
You still need to disable `language-javascript`

Edit2
atom-react is no longer maintained 🤦  I'll be on the lookout for it's replacement.
